
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vunhtasptubzduprcazy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1bmh0YXNwdHViemR1cHJjYXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzA1NjQsImV4cCI6MjA2MjgwNjU2NH0.g-22-e_-ykEroxm6hvQhmJgL-4HgSzfVQrGorpP7sfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      debug: true // Adicionar modo debug para ajudar na identificação de problemas
    }
  }
);
